apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: https
    port: 443
    targetPort: webhook-server
